### ISSUE TITLE
Recommended method for ReQL specific commands?

### ISSUE THREAD

**Issue by brezal** [almightycouch/rethinkdb_ecto#10]
Hi @almightycouch! Thanks for putting this together. What are your thoughts on working with changefeeds, geospatial queries, and other RethinkdDB specific operations?

**Comment by almightycouch** [comment]
Currently there is no way to run such operations via Ecto DSL.
You may want to use `RethinkDB.run/2` which is available as shortcut in your repository:

```elixir
defmodule MyApp.Repo do
  use Ecto.Repo, otp_app: :my_app
end

import RethinkDB.Query

feed =
  table("users")
  |> changes
  |> MyApp.Repo.run
```

This is not perfect, and in future it may be possible to use `Ecto.Schema` to run such queries:

```elixir
import RethinkDB.Query

feed =
  MyApp.User
  |> MyApp.Repo.changes
  |> MyApp.Repo.run
```

or even

```elixir
import RethinkDB.Query

feed =
  from(u in MyApp.User, where: u.age > 18)
  |> MyApp.User.changes
  |> MyApp.User.run
