### ISSUE TITLE
Embeded documents values are not being returned on Insert

### ISSUE THREAD

**Issue by jfayad** [almightycouch/rethinkdb_ecto#26]
I have a schema declaring an embeds_many element the embedded document is declared as an embedded_schema.
Whenever I insert a main document in the DB the return object has empty values for the embedded object, yet if I query the DB for this same element I get the full values.

Here is an illustration:

```elixir
# I'm using Phoenix so this is inside the models folder
defmodule Smartcat.Team do
    use Smartcat.Web, :model
    schema "teams" do
        field :name, :string
        embeds_many :spaces, Smartcat.Space
    end
end

defmodule Smartcat.Space do
    use Smartcat.Web, :model
    embedded_schema do
        field :name, :string
        field :assignedUsers, :map
        field :autopilots, :map
    end
end
```

```elixir
iex(5)> team = %Smartcat.Team{name: "TestTeam", spaces: [%Smartcat.Space{name: "TestSpace"}]}      
%Smartcat.Team{__meta__: #Ecto.Schema.Metadata<:built, "teams">, id: nil,
 name: "TestTeam",
 spaces: [%Smartcat.Space{assignedUsers: nil, autopilots: nil, id: nil,
   name: "TestSpace"}]}
   
iex(6)> Smartcat.Repo.insert(team)                                                                 
{:ok,
 %Smartcat.Team{__meta__: #Ecto.Schema.Metadata<:loaded, "teams">,
  id: "96e2a65e-e272-4119-b1f8-392d7ca024b1", name: "TestTeam",
  spaces: [%Smartcat.Space{assignedUsers: nil, autopilots: nil, id: nil,
    name: nil}]}}
iex(9)> Smartcat.Team |> Ecto.Query.first |> Smartcat.Repo.one
%Smartcat.Team{__meta__: #Ecto.Schema.Metadata<:loaded, "teams">,
 id: "96e2a65e-e272-4119-b1f8-392d7ca024b1", name: "TestTeam",
 spaces: [%Smartcat.Space{assignedUsers: nil, autopilots: nil,
   id: "602fdf1b-54d5-43ef-b40f-4db671738210", name: "TestSpace"}]}
```

**Comment by redrabbit** [comment]
Hi @jfayad, thank you for notifying.

Pretty sure `:embeds_one` and `:embeds_many` has changed between Ecto 1.x and 2.x. 
I will investigate this and add some tests to cover embedded fields.

**Comment by jfayad** [comment]
Thank you @redrabbit and you are welcome.

Let me know if I can be of any help here... I'm still new to Elixir/Phoenix/Ecto/RethinkDB but very enthusiastic about it.

**Comment by jfayad** [comment]
Hey @redrabbit I also spotted an issue with ecto itself. 

I don't know if this needs to be considered in here too so this works with rethinkdb or if this will work immediately after it's fixed on ecto ?

Here is the issue: https://github.com/elixir-ecto/ecto/issues/1837#issuecomment-265775648

**Comment by redrabbit** [comment]
I did add some tests for `embedded_schema`. Somehow, this issue seems to be fixed already.

Please, reopen if you still have problems.
