### ISSUE TITLE
Querying Repo.get/1 with :binary_id 

### ISSUE THREAD

**Issue by bAmpT** [almightycouch/rethinkdb_ecto#28]
It's maybe worth mentioning that you have to change the id type of the model to `:binary_id` in order to make it work.. I think this should go in the README somewhere.

web/web.ex:
```
def model do
    quote do
      ...
      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
end
```

**Comment by redrabbit** [comment]
Actually, this is stated in the [**Known Limitation**](https://hexdocs.pm/rethinkdb_ecto/RethinkDB.Ecto.html) section in the docs. Maybe I should add a section to the README too.
