### ISSUE TITLE
problem with floats

### ISSUE THREAD

**Issue by Fulnir** [almightycouch/rethinkdb_ecto#30]
Hi,
I have some float fields in my schema. (Also in a embedded_schema)

Saving **123.4** works fine. But **123.0** is saved as **123** (Integer?)
When I read from database with MyApp.Repo.get_by(s_id: the_user.s_id) I got the error 

"cannot load `123` as type :float for :distance in schema MyApp.User"

I started this month with Elixir. So I'm not sure, if I doing something wrong, or if it is a bug.

**Comment by redrabbit** [comment]
It may be a bug,  Ecto provides special types such as `#Decimal<>` which are currently not explicitely supported by the adapter.

I'm until mid march in the Phillipines without laptop and the connection here is really not that good. Will have a look at this when I'm back.
