### ISSUE TITLE
Ecto 2.0 query prefix not working

### ISSUE THREAD

**Issue by setras** [almightycouch/rethinkdb_ecto#33]
Hi,
I'm writing a multi tenancey application where each user account should have his own database in rethinkdb. Ecto 2.0 introduced the query prefixes feature that gives me the needed functionality to specify the database when executing a query.

Currently your adapter does not support this feature but I had a look at the "normalized_query.ex" file and found at line 82 following statement:

```elixir
defp from(%{source: {_prefix, table}}), do: ReQL.table(table)
```

Would it work if I change this line to:

```elixir
defp from(%{source: {prefix, table}}), do: ReQL.db(prefix).table(table)
```

Thanks, Stefan

**Comment by redrabbit** [comment]
As RethinkDB doed not provide specific support for multi-tenancy such as Postgres DDL schemas, the best was would be to use different databases.

I'm not really familiar with Ecto 2.0 support for prefixes but I think it provides multiples scopes (globally, per-query, etc.).

Changing the line to use the prefix should work for per-query prefixes. Global prefix support has to be added independently on the connection itself (should not be too hard to support).

Also, some changes would be requiered to work with migrations.

I'm until mid march in the Phillipines without laptop and the connection here is really not that good. Will have a look at multi-tenancy when I'm back.

**Comment by redrabbit** [comment]
Closing this as RethinkDB does not support multi-tenancy. Not clear how a fix could be implemented correctly.
