### ISSUE TITLE
migration with multi index

### ISSUE THREAD

**Issue by mkaravaev** [almightycouch/rethinkdb_ecto#36]
how can I create migration with multi index?
`create index(:dialogs, [:participants], multi: true)` this not working, it creates index but in index status it has `multi: false`

UPD: found how to fix this can I make PR?

**Comment by redrabbit** [comment]
The `:multi` and `:geo` options are RethinkDB specific and not allowed in `%Ecto.Migration.Index{}`.
Perhaps, we can use the `:options` field from `%Ecto.Migration.Index{}` to pass `:multi` and `:geo`.

I'm not really sure how the `:options` is interpreted by Ecto, it typespec is defined as `String.t` so I think it is used to pass options directly to the underlying SQL adapter. Using this field to pass a keyword list will raise a type error with Dialyzer but it seems to be the best option to support these RethinkDB specific features.

**Comment by redrabbit** [comment]
@mkaravaev, if you have a different implementation approach, please share your ideas.

**Comment by mkaravaev** [comment]
yes I use options field
