### ISSUE TITLE
hex.pm

### ISSUE THREAD

**Issue by alec-c4** [almightycouch/rethinkdb_ecto#6]
Hi,
could you please publish your work on hex.pm?

**Comment by almightycouch** [comment]
Hi @alec-c4,
i will definitely publish a hex package once this projects reach more maturity.

For now it is more a (working) experiment but I need more time to get things work properly.
My main goal is to have an Ecto 2.0 adapter for RethinkDB. With support for connection pools (see `DBConnection`), many-to-many relationship and subqueries.

Some crucial things such as documentation and integration tests with Ecto are missing and must be added before I get my package published.

Until then, you will have to use
```elixir
{:rethinkdb_ecto, github: "almightycouch/rethinkdb_ecto"}
```
to play around.
