### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by cgarciae** [almightycouch/rethinkdb_ecto#8]
Currently the paramter `db:` is not being passed to `RethinkDB.Connection.start_link`, therefore everything runs on the `test` database. This could be easily fixed by adding a few lines to `RethinkDB.Ecto.start_link` like this

```
  def start_link(repo, opts) do
    {:ok, _} = Application.ensure_all_started(:rethinkdb)

    if opts[:database] do
      opts = Keyword.put(opts, :db, opts[:database])
    end

    repo.__connection__.start_link(opts)
  end
```

Already tested locally and it works. Currently I am just using this for migrations while the project matures.

**Comment by almightycouch** [comment]
Hi @cgarciae,

I'm currently putting some effort to get things work with the new Ecto 2.0 version (currently, RC4). Have a look at the [`ecto_2`](https://github.com/almightycouch/rethinkdb_ecto/tree/ecto_2) branch.

If you want to have this feature with Ecto < 2.0, please make a pull request.

Thanks
